### ISSUE TITLE
Dependencies installation problem

### ISSUE THREAD

**Issue by abo88od** [madhavmk/QA_VoiceBot_Desktop_Application#2]
Hello everyone,
I tried to set a virtual environment in anaconda and install all required dependencies from the .yml file using this:
conda env create -f  Windows_Anaconda_Environment.yml
but it installed just the first part without the pip list.
so I copied all requested pip list to a txt file and installed them using pip install -r requirements.txt and it works fine except the TensorFlow where the default version installed is the GPU version, therefore I installed it separately with pip install --ignore-installed --upgrade tensorflow==1.12
however, I still get this message:
 "Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2"
however, the code works fine. but it is slow, and the STT isn't accurate.

**Comment by madhavmk** [comment]
**Regarding the Speech to Text conversion:** 

The pretrained Deepspeech model we use works works most accurately with for American Male English sampled at a 40kHz rate. We recommend downloading your question audio from an online generator such as IBM Watson's : [https://text-to-speech-demo.ng.bluemix.net/?_ga=2.55966188.673030515.1577624344-880558420.1577624344&cm_mc_uid=70936574787615776243433&cm_mc_sid_50200000=83024581577627214288&cm_mc_sid_52640000=10941271577627214295](url)

**Regarding the Slow processing time:**

Yes. The whole Audio recognition --> Question Answering --> Speech generation pipeline is quite resource intensive! As a benchmark, my laptop having 8GB RAM, and a 4GB integrated graphics card takes 150-200 seconds for a single question (with full CPU and GPU utilization). Our aim was to do the S2T and T2S conversion on the local system instead of using a readymade online API; which has a drawback of being slower and more resouce-hungry.

Additionally, the WavecodeRNN Text to Speech conversion might produce garbage audio at the tail end of lengthy Answers. In this case, use the Tacatron2 model which has a lesser processing overhead, but produces les realistic output Audio.

For reference, could you post your computer specs and question answering processing time here.

**Comment by abo88od** [comment]
I use a windows 10 machine with 8 GB RAM and CPU I5 1,7-2.4 GHz with no dedicated GPU.

**Comment by anujstam** [comment]
@abo88od  Has the issue been resolved?

**Comment by abo88od** [comment]
yes thank you all
